### ISSUE TITLE
Run offline demo

### ISSUE THREAD

**Issue by fazliimam** [engindeniz/vitis#1]
Great work!
Can you provide trained weights and code to run inference locally on my own videos?

**Comment by engindeniz** [comment]
Thank you for your interest in our project!

We currently do not provide a dedicated script for running inference on individual videos. However, you can still apply inference to your videos by following the raw data processing pipeline provided in our repository and using our available pretrained models for [Zero-Shot Evaluation](https://github.com/engindeniz/vitis#zero-shot-evaluation). For more detailed instructions, please refer to the `README.md` file.
