### ISSUE TITLE
visual prompts arguments

### ISSUE THREAD

**Issue by Songinpyo** [engindeniz/vitis#2]
First of all, thanks to your great work!

I wonder about the arguments related with "visual prompts".
To run your code on custom dataset I'm preparing to extract features.

When I tried to extract visual features, i got some troubles.

```bash
self.encoder = CLIPEncoder(config, self.args.prompt_type, self.args.visual_prompt_projection_factor,
AttributeError: 'Namespace' object has no attribute 'visual_prompt_projection_factor'
```

Actually, not only about 'visual_prompt_projection_factor'.
I also can't find about these informations in your args file.
```python
        self.encoder = CLIPEncoder(config, self.args.prompt_type, self.args.visual_prompt_projection_factor,
                                   self.args.visual_prompt_projection_layer, self.args.visual_model_hidden_size,
                                   self.args.visual_prompt_num_layer, self.args.visual_prompt_num_tokens,
                                   self.args.visual_prompt_initialization, self.args.visual_prompt_patch_size,
                                   self.args.visual_prompt_dropout_rate, self.args.visual_prompt_like_linear_layer_each_transformer_layer)
```

And when extract the features, I think we would not use promts and projections right?
Would you help me to shoot this troubles?

I think this will affect to follow-up tasks like training and testing.

**Comment by engindeniz** [comment]
Thank you for your interest in our project!

The CLIPEncoder mentioned is incorporated exclusively within our model's architecture. It is not used for feature extraction. You can check [Raw Data Processing Guidelines](https://github.com/engindeniz/vitis?tab=readme-ov-file#raw-data-processing-guidelines) and use [this code](https://github.com/engindeniz/vitis/blob/main/extract/extract_video_features.py) to extract features for a custom dataset.

**Comment by Songinpyo** [comment]
Thanks for your answering.

Unfortunately code url which you provided is expired.

And I'm not asking only about feature extraction but also the running code.
There is no args for visual prompts in "args.py" file.
